### ISSUE TITLE
可能是Bug吧

### ISSUE THREAD

**Issue by lydlovezjr** [Beseting/PlanA#4]
else if (cls == RelativeLayout.class) {//相对布局
            RelativeLayout relativeLayout = (RelativeLayout) mRootView;
            relativeLayout.addView(rlTitleBar, 0);
        }
相对布局如果这样添加标题栏的话,位置显示不正确!!!

**Comment by Beseting** [comment]
如果根布局是相对布局的话，在注入标题栏布局后会默认在顶部，这个时候的Activity的xml布局内容就需要在写好的内容上，加个上边距（50dp），然后就不会覆盖标题栏了
